name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: hostname
